# Generated by Django 5.2.6 on 2025-09-07 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.capitulo')),
            ],
        ),
    ]
